name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build with Gradle
      env:
        GIT_BRANCH: ${{ github.ref }}
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_TOKEN_DEV: ${{ secrets.DISCORD_TOKEN_DEV }}
      run: ./gradlew build
    - name: Deploy Docker Image
      env:
        GIT_BRANCH: ${{ github.ref }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: ./gradlew jib
