name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12
    - name: Build with Gradle
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        DISCORD_TOKEN_DEV: ${{ secrets.DISCORD_TOKEN_DEV }}
      run: ./gradlew build
    - name: Deploy Docker Image
      run: ./gradlew jib -PDockerPassword=${{ secrets.DOCKER_PASSWORD }}
